language: node_js
script: make test-sauce
node_js:
- '0.11'
env:
  matrix:
  - BROWSER='ie6'
  - BROWSER='ie7'
  - BROWSER='ie8'
  - BROWSER='ie9'
  - BROWSER='ie10'
  - BROWSER='ie11'
  global:
  - secure: cyU2Ci7F7E6fsf9Bt3ElO7AB5VKOs+6fMOWSxmvzIj+zegSojR6JhdXce/0EWQQTJ8bzICh/IbuGYzMAYYBRXFJtVKdl236HXUp5BmSJzitEAljwq1U4goKebRFR47gqTbCjASC7Io6yNP7dhczs9pdnx52juXHJaEWnn8lDoKk=
  - secure: ZZ6yeRILaSo494Bnjw6QjDos5YZO4L/IQllZmAcu2kH8HpgkjD/sE3M3H9aOroG+v6b9DvQ/bS0vKaTa3fTAFZCwOMcM8QI583vgn8KV8GNSEXoxG4mUSbni7ghyMcxIlRe8O3W96p5ZqwHHTeOo5ERvFO1NEbD1Q8+sgmy3XqA=
  - secure: AU+vNsbDROWI/5uwybZhzzzWDKqx7TAizc1qykAAFPn3Y+4T/NEGWHfJSm0qByL46tHS/Bvays1fSZOgr6bVX30rYShIl5AOcqTwE2IdTSEIrOZmP1bewOLOVWISm6dvJc/MfGnEpu9hsfHG9witfP0EJQ5M5in4WPMeB77Mt2w=
  - secure: V5DkDycKMmP+BZQZdRS3HTi7/wMzNEEk5FCM/8EORfH5qymSAq4OirrdSghmKzbHozGRUsBRAu6Uf9QcSI4twpHfG+wP2JIJrCL++jlb+TT4bFeTWIpDy+Nypzvcer6gdowHya3CfbWF9KPv/XgubAkNmfr6Uz5pA/TStApCTwQ=
